image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent
appMessage: "Shipping Service"

service:
  port: 80

serviceAccount:
  create: true  # Add this line to control ServiceAccount creation
  automount: true 
